spring:
  application:
    name: attestation03
  jpa:
    show-sql: true

  flyway:
    user: postgres
    password: postgres
    default-schema: tires
    url: jdbc:postgresql://localhost:5432/tires_db

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tires_db?currentSchema=tires
    username: postgres
    password: postgres

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter=method: